name: Update from template
"on":
  schedule:
    - cron: "00 00 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  merge:
    name: Update from template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Run update script
        run: bash update.sh

      - name: Commit changes back to repository
        uses: EndBug/add-and-commit@v9.1.4
        with:
          commit: --signoff
          default_author: github_actor
          fetch: true
          message: 'ci: update from template'
